#!/usr/bin/expect -f

##
#
# Title:		RPC2 Trap Configurator
# Description:  Create SNMP v1/v2c Trap Entry
# Version:		0.1
# Authors: 		scott.donaldson@vertiv.com
# Usage:		n/a
# Inputs:
#	RPC2_AUTH_USERNAME
#	RPC2_AUTH_PASS
#	RPC2_SNMP_TRAP_MODE 		- STRING [snmpv1|snmpv2]
#	RPC2_SNMP_TRAP_LGPMIB 		- STRING [enable|disable]
#	RPC2_SNMP_TRAP_MIBTRAPS 	- STRING [enable|disable]
#
set ip [lindex $argv 0]
set timeout 10
spawn ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -l $env(RPC2_AUTH_USERNAME) $ip
expect "*assword:"
send "$env(RPC2_AUTH_PASS)\r"
expect "SUCCESS"
expect "cli-> "
send "snmp v1v2 enable\r"
expect "cli->"

send "snmp lgpmib enable\r"
expect "cli->"
send "snmp mibtraps enable\r"
expect "cli->"
send "snmp traps $env(RPC2_SNMP_TRAP_MODE)\r"
expect "cli->"

expect eof
